pipelines:
  default:
    - step:
        name: Deploy on FTP.
        deployment: production
        image: php:7.2
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - apt-get -qq install git-ftp
          - composer install
         
          # 1st run use "init", after use "push" :
#          - git ftp init --user "$FTP_USERNAME" --passwd "$FTP_PASSWORD" ftp://$FTP_HOST/$FTP_FOLDER
          - git ftp push --user "$FTP_USERNAME" --passwd "$FTP_PASSWORD" ftp://$FTP_HOST/$FTP_FOLDER
